# config.yaml
path: C:\Users\023\PycharmProjects\opncv\dataset # Путь к папке с вашим датасетом
train: C:\Users\023\PycharmProjects\opncv\dataset\images # Путь к папке с тренировочными изображениями
val: C:\Users\023\PycharmProjects\opncv\dataset\images # Путь к папке с валидационными изображениями
nc: 2 # Укажите количество классов в вашем датасете
names: ['Roki-2', 'Walker'] # Список с названиями классов